import { StyleSheet } from "react-native";
import { Color, Border, FontSize} from "../contants";

const styles = StyleSheet.create({
  scrollView: {
    flexGrow: 1,
    justifyContent: "center",
    alignItems: "center",
  },
  listmonanLayout: {
    width: 439,
    position: "absolute",
  },
  orderbtnLayout: {
    height: 21,
    position: "absolute",
  },
  xemTypo: {
    fontWeight: "700",
    fontSize: FontSize.size_mini,
    textAlign: "left",
    height: 21,
  },
  monNgonLayout: {
    width: 141,
    position: "absolute",
  },
  childBorder: {
    borderWidth: 2,
    borderStyle: "solid",
  },
  monNgonItemPosition: {
    height: 96,
    left: 10,
    top: 13,
    borderRadius: Border.br_xl,
    position: "absolute",
  },
  textTypo: {
    fontSize: FontSize.size_smi,
    fontWeight: "700",
    height: 21,
    position: "absolute",
  },
  textPosition: {
    left: 11,
    width: 119,
  },
  muaTypo: {
    width: "100%",
    color: Color.gray_100,
    textAlign: "center",
    fontSize: FontSize.size_lg,
    fontWeight: "700",
    height: 21,
    position: "absolute",
  },
  iconfeatherIconLayout1: {
    height: 16,
    width: 16,
    position: "absolute",
    overflow: "hidden",
  },
  wrapperPosition: {
    top: 196,
    height: 41,
    left: 10,
    position: "absolute",
  },
  khuyenmaiLayout: {
    height: 138,
    width: 369,
    // position: "absolute",
    marginTop:10
  },
  giaTypo: {
    left: 163,
    textAlign: "left",
    fontWeight: "700",
    fontSize: FontSize.size_mini,
    position: "absolute",
  },
  giaLayout: {
    height: 25,
    width: 77,
  },
  buttonPosition: {
    left: -1,
    top: -5,
    borderRadius: Border.br_xl,
    position: "absolute",
    borderWidth: 1,
    backgroundColor: Color.orangered_200,
    borderColor: Color.darkorange_200,
    alignItems: "center",
  },
  buttonIcon: {
    width: 102,
    height: 23,
  },
  DatNgayTypo: {
    fontSize: FontSize.size_xs,
    height: 16,
    fontWeight: "700",
    position: "absolute",
  },
  topPosition: {
    height: 346,
    width: 414,
    left: 0,
    top: 20,
    position: "absolute",
  },
  searchLayout: {
    height: 49,
    width: 369,
    position: "absolute",
  },
  profileLayout: {
    height: 32,
    position: "absolute",
  },
  chuongLayout: {
    height: 51,
    position: "absolute",
  },
  tichdiemPosition: {
    left: 186,
    position: "absolute",
  },
  home1Layout: {
    width: 50,
    position: "absolute",
  },
  vectorIconLayout: {
    maxHeight: "100%",
    maxWidth: "100%",
    position: "absolute",
    overflow: "hidden",
  },
  notifyLayout: {
    height: 24,
    width: 27,
    top: 0,
    position: "absolute",
  },
  bgLayout: {
    width: 125,
    height: 39,
    position: "absolute",
  },
  menuPosition: {
    width: 21,
    left: 0,
    position: "absolute",
  },
  salesTypo: {
    height: 11,
    color: Color.orangered_100,
    fontSize: FontSize.size_7xs,
    textAlign: "left",
    fontWeight: "700",
    top: 0,
  },
  iconfeatherIconLayout: {
    height: 22,
    width: 22,
    position: "absolute",
  },
  DatHangLayout: {
    width: 23,
    position: "absolute",
  },
  profilesLayout: {
    width: 31,
    position: "absolute",
  },
  breakpageIcon: {
    top: 735,
    left: 32,
    width: 351,
    height: 1,
    position: "absolute",
  },
  monNgonPhaiThu: {
    width: 198,
    textAlign: "left",
    color: Color.white,
    left: 0,
    top: 0,
    position: "absolute",
  },
  xemtatca: {
    left: 241,
    color: "#fffdfd",
    width: 147,
    textAlign: "left",
    top: 0,
    position: "absolute",
  },
  monngontxt: {
    width: 388,
    left: 8,
    top: 0,
  },
  monNgonChild: {
    borderColor: "#fd8d26",
    backgroundColor: Color.gray_900,
    borderWidth: 2,
    borderRadius: Border.br_xl,
    left: 0,
    top: 0,
    width: 141,
    position: "absolute",
    height: 237,
  },
  monNgonItem: {
    width: 121,
  },
  monAnRatNgon: {
    top: 121,
    height: 39,
    width: 119,
    textAlign: "center",
    color: Color.black,
    fontSize: FontSize.size_smi,
    left: 11,
    fontWeight: "700",
    position: "absolute",
  },
  text: {
    top: 160,
    color: Color.saddlebrown,
    width: 119,
    textAlign: "center",
    left: 11,
  },
  buybtnChild: {
    height: 40,
    borderRadius: Border.br_3xs,
    borderWidth: 2,
    backgroundColor: Color.orangered_100,
    borderColor: Color.orangered_200,
    left: "5%",
    top: "80%",
    width: 125,
    position: "absolute",
  },
  muaNgay: {
    top: 8,
    alignItems: "center"
  },
  iconfeatherIcon: {
    left: 86,
    top: 13,
  },
  buybtn: {
    top: 197,
    height: 40,
    width: 200,
    position: "absolute",
  },
  monNgon: {
    height: 237,
    left: 0,
    top: 0,
    overflow: "hidden",
  },
  vectorIcon: {
    width: 119,
  },
  monNgonChild1: {
    borderRadius: Border.br_3xs,
    width: 119,
  },
  muaNgay1: {
    top: 207,
    left: 20,
  },
  iconfeatherIcon1: {
    top: 259,
    left: 395,
  },
  monNgon1: {
    left: 298,
    height: 237,
    top: 0,
  },
  icon: {
    height: "100%",
    borderRadius: Border.br_3xs,
    width: "100%",
  },
  wrapper: {
    width: 121,
  },
  iconfeatherIcon2: {
    top: 210,
    left: 97,
  },
  monNgon2: {
    left: 149,
    height: 237,
    top: 0,
  },
  listmonan: {
    top: 49,
    height: 237,
    left: 0,
  },
  groupmonan: {
    top: 392,
    height: 286,
    left: 21,
    overflow: "hidden",
  },
  khuyenmaiSp: {
    width: 182,
    textAlign: "left",
    color: Color.white,
    left: 0,
    top: 0,
    position: "absolute",
  },
  xemtatca1: {
    width: 120,
    textAlign: "left",
    color: Color.white,
  },
  xemtatcaContainer: {
    left: 255,
    top: 0,
    position: "absolute",
  },
  khuyenmaitext: {
    width: 375,
    left: 2,
    top: 0,
  },
  monkhuyenmaiChild: {
    borderWidth: 2,
    borderStyle: "solid",
    borderColor: "#fd8d26",
    backgroundColor: Color.gray_900,
    borderRadius: Border.br_xl,
    left: 0,
    top: 0,
  },
  imgIcon: {
    top: 8,
    height: 124,
    left: 7,
    borderRadius: Border.br_xl,
  },
  comboMonKhuyenMai: {
    top: 27,
    width: 184,
    height: 48,
    color: Color.black,
  },
  gia: {
    top: 91,
    left: 163,
    textAlign: "left",
    fontWeight: "700",
    fontSize: FontSize.size_mini,
    position: "absolute",
    color: Color.saddlebrown,
  },
  DatNgay: {
    top: 2,
    width: 101,
    textAlign: "center",
    color: Color.black,
    left: 0,
  },
  orderbtn: {
    top: 93,
    left: 254,
    width: 101,
  },
  monkhuyenmai: {
    left: 2,
    top: 0,
  },
  listmonkm: {
    top: 52,
    width: 371,
    height: 444,
    left: 0,
    position: "absolute",
  },
  groupkhuyenmai: {
    top: 764,
    left: 28,
    width: 377,
    height: 496,
    position: "absolute",
    overflow: "hidden",
  },
  sliderimg: {
    borderColor: "#fff",
    borderWidth: 2,
    borderStyle: "solid",
  },
  searchChild: {
    borderRadius: Border.br_xl,
    left: 0,
    top: 0,
  },
  searchicon: {
    right: 12,
    width: 32,
    height: 32,
    top: 9,
  },
  searchinput: {
    left: 14,
    top: 9,
    height: 32,
    position: "absolute",
  },
  search: {
    top: 91,
    left: 21,
  },
  avatarIcon: {
    width: 32,
    height: 32,
    left: 0,
    top: 0,
  },
  ngocQuach: {
    top: 5,
    left: 40,
    width: 86,
    textAlign: "left",
    color: Color.white,
  },
  profile: {
    top: 14,
    width: 126,
    left: 0,
  },
  tichdiemChild: {
    width: 79,
    height: 27,
  },
  tichDiemtext: {
    width: 64,
    top: 4,
    left: 7,
    textAlign: "center",
    color: Color.white,
  },
  tichdiem: {
    top: 17,
    height: 25,
    width: 77,
  },
  chuongbg: {
    top: 6,
    borderRadius: 9,
    backgroundColor: Color.gray_800,
    borderColor: "#fdff9c",
    height: 45,
    borderWidth: 2,
    borderStyle: "solid",
    left: 0,
  },
  vectorIcon1: {
    height: "52.07%",
    width: "37.64%",
    top: "29.41%",
    right: "38.48%",
    bottom: "18.52%",
    left: "23.88%",
  },
  notifyChild: {
    left: 0,
  },
  text6: {
    width: 11,
    top: 4,
    color: Color.black,
    textAlign: "left",
    left: 8,
  },
  notify: {
    left: 34,
  },
  chuong: {
    left: 318,
    width: 61,
    top: 0,
  },
  topnav: {
    width: 379,
    top: 4,
    left: 21,
  },
  homemain: {
    backgroundColor: Color.chocolate,
    flex: 1,
    height: 1340,
    overflow: "hidden",
    width: "100%",
  },
});

export default styles;
